- type: antag
  id: Changeling
  name: goob-roles-antag-changeling-name
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement # Imp
    time: 3600 # 1h
  - !type:DepartmentTimeRequirement # imp
    department: Security
    time: 2h
  playTimeTracker: AntagChangeling
  setPreference: true
  objective: goob-roles-antag-changeling-description
  guides: [ Changelings ]
