- type: antagGroup
  id: Nukies
  name: antag-group-Nukies
  color: "#ff0000"
  roles:
  - Nukeops
  - NukeopsMedic
  - NukeopsCommander

- type: antagGroup
  id: AntagOverall
  name: antag-group-Overall
  color: "#ff0000"
  roles:
  - Dragon
  - GenericAntagonist
  - GenericTeamAntagonist
  # - GenericFreeAgent
  - GenericSiliconAntagonist
  - SpaceNinja
  - Nukeops
  - NukeopsMedic
  - NukeopsCommander
  - ParadoxClone
  - HeadRev
  - Rev
  # - SubvertedSilicon
  - Thief
  - Traitor
  - TraitorSleeper
  # - Survivor
  - Wizard
  - InitialInfected
  - Zombie
  - Heretic
  - Changeling
  - BountyHunter
  - NukeopsLone
  - VRex

