- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement # Imp
    time: 3600 # 1h
  - !type:DepartmentTimeRequirement # imp
    department: Security
    time: 2h
  playTimeTracker: AntagHeretic
  setPreference: true
  objective: roles-antag-heretic-description
  guides: [ Heretics ]

- type: startingGear
  id: HereticGear
  storage:
    back:
    - CodexCicatrix
    - OrganHumanHeart
